/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 02 05:11:25 GMT 2019
 */

package als.pbt.lab4;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import als.pbt.lab4.MultiplyBoth;
import java.util.InputMismatchException;
import java.util.NoSuchElementException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.util.SystemInUtil;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class MultiplyBoth_ESTest extends MultiplyBoth_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SystemInUtil.addInputLine("6");
      SystemInUtil.addInputLine("7");
      String[] stringArray0 = new String[4];
      MultiplyBoth.main(stringArray0);
      assertEquals(4, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      int int0 = MultiplyBoth.multiplyBoth((-593), (-593));
      assertEquals(351649, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      int int0 = MultiplyBoth.multiplyBoth(2336, (-1176));
      assertEquals((-2747136), int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      String[] stringArray0 = new String[3];
      SystemInUtil.addInputLine("$oFBtuakHi%Rz!SdS*");
      // Undeclared exception!
      try { 
        MultiplyBoth.main(stringArray0);
        fail("Expecting exception: InputMismatchException");
      
      } catch(InputMismatchException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      int int0 = MultiplyBoth.multiplyBoth(0, 1398);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      String[] stringArray0 = new String[2];
      // Undeclared exception!
      try { 
        MultiplyBoth.main(stringArray0);
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      MultiplyBoth multiplyBoth0 = new MultiplyBoth();
  }
}
